name: our workflow for the Step-counter project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Main-CI:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Wenn du dennoch Build-Tools auf Windows brauchst, kannst du das behalten.
      - name: Windows Build Tools (nur wenn nötig)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
          choco install cmake

      - name: Install Lint- und Test-Tools
        run: |
          pip install ruff pytest

      - name: Lint with ruff
        run: |
          ruff check src tests --fix

      - name: Test with pytest
        run: |
          pytest -v || true
